### ISSUE TITLE
Write unit test for the feature: Non-existent user should not be able to fetch the documents

### ISSUE THREAD

**Issue by Naman-1234** [Naman-1234/BuildWebOnline-HacktoberFest#1]
Write unit-test to support the model:
https://github.com/Naman-1234/BuildWebOnline-HacktoberFest/blob/main/models/Files.js

and hence the feature:
Non-existent user should not be able to fetch the documents

**Comment by haripriyajk** [comment]
Hi,I am working on this @Naman-1234

**Comment by haripriyajk** [comment]
#16

**Comment by Naman-1234** [comment]
Got solved by:
https://github.com/Naman-1234/BuildWebOnline-HacktoberFest/pull/16
