### ISSUE TITLE
Write unit test for the feature: Non-existent User should not be able to log in

### ISSUE THREAD

**Issue by Naman-1234** [Naman-1234/BuildWebOnline-HacktoberFest#7]
Write unit-test to support the model:
https://github.com/Naman-1234/BuildWebOnline-HacktoberFest/blob/main/models/User.js

and hence the feature:
Non-existent User should not be able to log in

**Comment by nitish-420** [comment]
@Naman-1234 I have started working on this. Thanks

**Comment by Naman-1234** [comment]
Sure @nitish-420 , Assigned you the issue.

**Comment by Naman-1234** [comment]
Got solved by: https://github.com/Naman-1234/BuildWebOnline-HacktoberFest/pull/17
